name: Deploy Infrastructure

on:
  push:
    branches: [stage]

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    container: ghcr.io/openpipe/deploy-infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache NPM dependencies
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: infra/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('infra/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Pulumi deps
        run: npm install
        working-directory: infra

      - name: Run Pulumi
        run: pulumi up --stack=stage -f
        working-directory: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
